language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - ruby-head
  - jruby-head
  - rbx
  - ree
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
    - rvm: rbx
    - rvm: ree
    - rvm: jruby-head
    - jdk: openjdk6
  exclude:
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ree
      jdk: openjdk6
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7
    - rvm: rbx
      jdk: openjdk6
    - rvm: rbx
      jdk: openjdk7
    - rvm: rbx
      jdk: oraclejdk7

bundler_args: --without development
