language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - ruby-head
  - jruby-head
  - rbx
  - ree

gemfile:
  - gemfiles/0.8.gemfile
  - gemfiles/0.9.gemfile

jdk:
  -
  - openjdk7
  - oraclejdk7
  - openjdk6

matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
    - rvm: rbx
    - rvm: ree
    - rvm: jruby-head

  exclude:
    # remove ree from jdk matrix
    - rvm: ree
      jdk: openjdk7
    - rvm: ree
      jdk: oraclejdk7
    - rvm: ree
      jdk: openjdk6

    # remove rbx from jdk matrix
    - rvm: rbx
      jdk: openjdk7
    - rvm: rbx
      jdk: oraclejdk7
    - rvm: rbx
      jdk: openjdk6

    # remove 1.9.2 from jdk matrix
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: oraclejdk7
    - rvm: 1.9.2
      jdk: openjdk6

    # remove 1.9.3 from jdk matrix
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
    - rvm: 1.9.3
      jdk: openjdk6

    # remove 2.0.0 from jdk matrix
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: oraclejdk7
    - rvm: 2.0.0
      jdk: openjdk6

    # remove 2.1.0 from jdk matrix
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: oraclejdk7
    - rvm: 2.1.0
      jdk: openjdk6

    # remove ruby-head from jdk matrix
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: ruby-head
      jdk: oraclejdk7
    - rvm: ruby-head
      jdk: openjdk6

    # remove jruby-19mode and jruby-head from non-jdk matrix
    - rvm: jruby-19mode
      jdk:
    - rvm: jruby-head
      jdk:

bundler_args: --without test
