language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - ruby-head
  - jruby-head
  - rbx
  - ree
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: ruby-head
    - rvm: rbx
    - rvm: ree
    - rvm: jruby-head

bundler_args: --without test
